// <auto-generated />
using System;
using FastPay.Transactions.Infra.Data.Sql.DataBase.v1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastPay.Transactions.Infra.Data.Sql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260526163832_AddTransactionsTable")]
    partial class AddTransactionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastPay.Transactions.Domain.Entities.v1.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("account_id");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("client_id");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.HasKey("Id");

                    b.ToTable("Tb_Accounts", (string)null);
                });

            modelBuilder.Entity("FastPay.Transactions.Domain.Entities.v1.AccountSequence", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("client_id");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int")
                        .HasColumnName("last_number");

                    b.HasKey("ClientId");

                    b.ToTable("Account_Sequences", (string)null);
                });

            modelBuilder.Entity("FastPay.Transactions.Domain.Entities.v1.ClientSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastNumber")
                        .HasColumnType("int")
                        .HasColumnName("last_number");

                    b.HasKey("Id");

                    b.ToTable("Client_Sequences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastNumber = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
